lib/bad_pinoy_movies_web/router.ex
defmodule BadPinoyMoviesWeb.Router do
  use BadPinoyMoviesWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug BadPinoyMoviesWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BadPinoyMoviesWeb do
    pipe_through :browser

    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/videos", VideoController
    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", BadPinoyMoviesWeb do
  #   pipe_through :api
  # end
end

lib/bad_pinoy_movies_web/views/layout_view.ex
defmodule BadPinoyMoviesWeb.LayoutView do
  use BadPinoyMoviesWeb, :view
end

lib/bad_pinoy_movies_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= assigns[:page_title] || "BadPinoyMovies · Phoenix Framework" %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <%= csrf_meta_tag() %>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <%= if @current_user do %>
              <li><%= @current_user.name %></li>
              <li>
                <%= link("Log out", to: Routes.session_path(@conn, :delete, @current_user), method: :delete) %>
              </li>
            <% else %>
              <li><%= link("Register", to: Routes.user_path(@conn, :new)) %></li>
              <li><%= link("Log in", to: Routes.session_path(@conn, :new)) %></li>
            <% end %>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>